name: Triage Bot

# Run when an issue is created.
on:
  issues:
    types:
      - opened

# All permissions not specified are set to 'none'.
permissions:
  issues: write

jobs:
  triage_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AmosHuKe/test_triage_bot

      - uses: dart-lang/setup-dart@v1

      - run: dart pub get

      # Delay 1 minutes to allow a grace period between opening or transferring
      # an issue and assigning an area- label.
      - name: sleep 1m
        run: sleep 60

      - name: triage issue
        env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: dart bin/triage.dart $ISSUE_URL